### ISSUE TITLE
emailqueue not trigger mail

### ISSUE THREAD

**Issue by nikhiladmuthe** [tin-cat/emailqueue#16]
Hello,

I have AWS EC2 instance. I have integrated emailqueue but when I trying to send email its added into database  but mail can't send and "Messages in queue" is increment. Please do me needful help.  

Thank you
![emailqueue-error](https://user-images.githubusercontent.com/39026857/44193056-4d874880-a14f-11e8-9cca-ea335733b82d.jpg)

**Comment by tin-cat** [comment]
Hi @nikhiladmuthe it seems you haven't set up the cronjobs emailqueue needs. Take a look at the "How to install" section on the README.md file for info on how to do it.

It you did this but your emails are not being delivered, i would recommend you to re-check that you've configured your SMTP server properly on config/application.config.inc.php

Also, I would take a look at your php/web server error log while at the same time running the delivery script to check if there are some errors being thrown out while trying to send the emails, or maybe some syntax errors in application.config.inc.php

Hope this helps you, cheers!

**Comment by nikhiladmuthe** [comment]
Hello,

Please find my coding and syslog and auth log on aws server.

Below is my code
*application.config.inc.php - *
<?php
define("FRONTEND_USER", "admin"); // The user name for the frontend
define("FRONTEND_PASSWORD", "admin"); // The password for the frontend

define("QUEUED_MESSAGES", 40); // Number of last queued messages to show in
frontend
define("LATEST_DELIVERED_MESSAGES", 10); // Number of last delivered
messages to show in frontend
define("LATEST_CANCELLED_MESSAGES", 10); // Number of last cancelled
messages to show in frontend
define("MAXIMUM_DELIVERY_TIMEOUT", 50); // Maximum seconds Emailqueue
should spend sending queued emails everytime it's called. Keep this smaller
than the amount of time between calls to the delivery script (e.g. If
you're calling delivery every 60 seconds, keep this at something like 50 to
avoid accumulating instances of Emailqueue eating resources)
define("DELIVERY_INTERVAL", 10); // Hundredths of a second between each
email send. Use this to be more friendly to SMTP servers, should be a
balance between being friendly and the number of emails you need to send
per seconds in order to keep your queue clean.
define("MAX_DELIVERS_A_TIME", 1000); // Number of maximum messages to
deliver every time delivery script is called. Anyway, this is better
controlled with the MAXIMUM_DELIVERY_TIMEOUT configuration above.
define("SENDING_RETRY_MAX_ATTEMPTS", 3); // Maximum number of attemps to
send a message if error is found.
define("PURGE_OLDER_THAN_DAYS", 5); // Purge messages older than this days
from the database. Depending on the amount of emails you send, use this
setting to keep your sent emails database to grow too big. It should be a
balance between how big would you like to keep your sent emails history and
how responsive would you like emailqueue to be. Smaller database will make
emailqueue run faster when specially inserting new emails.
define("SEND_METHOD", "smtp"); // Set it to either "smtp" or "sendmail" to
choose the method for delivering emails. If "smtp" is choosen, at least the
SMTP_SERVER below must be set.
define("SMTP_SERVER", "127.0.0.1"); // The IP of the SMTP server
define("SMTP_PORT", 25); // The port of the SMTP server
define("SMTP_IS_AUTHENTICATION", false); // True to use SMTP server
Authentication
define("SMTP_AUTHENTICATION_USERNAME", "");
define("SMTP_AUTHENTICATION_PASSWORD", "");
define("CHARSET", "utf-8"); //Used in Content-Type Email Header
define("CONTENT_TRANSFER_ENCODING", "8bit"); //Content-Transfer-Encoding
Email Header. May be 7bit, 8bit, quoted-printable or base64

define("PHPMAILER_LANGUAGE", "en");
define("DEFAULT_TIMEZONE", "Asia/Kolkata");

define("LOGS_DIR", "logs"); // The directory to store logs
define("LOGS_FILENAME_DATEFORMAT", "Y-m-d"); // The file name format for
log files, as a parameter for the PHP date() function
define("LOGS_DATA_DATEFORMAT", "Y-m-d H:i:s"); // The format of the date as
stored inside log files, as a parameter for the PHP date() function

    define("IS_DEVEL_ENVIRONMENT", true); // When set to true, only emails
addressed to emails into $devel_emails array are sent

    $devel_emails = array(
        "me@email.com"
    );
?>

*db.config.inc.php*
<?php

define("DB_HOST", "127.0.0.1");
define("DB_UID", "root");
define("DB_PWD", "");
define("DB_DATABASE", "indiaclick_mailqueue");

?>

Please look into matter and help me out of this. I am stuck. :(


Regards
Nikhil Admuthe

**Comment by tin-cat** [comment]
Hi @nikhiladmuthe,

I'm sorry I don't provide specific technical support your config files look ok but that doesn't provides any information on the errors you're having. Please take a look at the recommendations I gave you in my first reply, and find search from an experienced programmer or sysadmin if you don't understand/know how to address the recommendations.

Cheers.

**Comment by nikhiladmuthe** [comment]
Hello,

When i directly call delivery.php then it show following message on screen.
"Emailqueue · Delivery
Reminder: Running in development environment, no emails will be sent."

I check cron status its work fine. No error log and system log having email errors

**Comment by tin-cat** [comment]
Hi, in config/application.config.inc.php, set IS_DEVEL_ENVIRONMENT to false

It should work.
