### ISSUE TITLE
Thanks for the update

### ISSUE THREAD

**Issue by Organizer21** [tin-cat/emailqueue#18]
It just crossed my mind to check on emailqueue today and was very happy to see there had been an update. I'll be updating my tiny implementation soon and love the emailqueue_inject::inject parameter option! Hope there's more improvements and updates due :) keep up the good work.

**Comment by tin-cat** [comment]
Thanks @Organizer21! Remember the call to the emailqueue_inject::inject method has now a different syntax! cheers!
