### ISSUE TITLE
Install emailqueue without Composer

### ISSUE THREAD

**Issue by w4r0** [tin-cat/emailqueue#20]
Hi, is it possible to install emailqueue without Composer? As I'm going to use it in a shared hosting.

**Comment by tin-cat** [comment]
Hi! I'm sorry to say there is no official guide to use Emailqueue without Composer, but you should be able to do so as long as you include all the needed libraries you'll found on composer.json.

Another way to install Emailqueue in a shared hosting would be to first install it in your local computer, where you'll be able to execute `composer update`, and then upload the resulting folder to the shared hosting. I haven't tested this but I'm guessing it should work!

Cheers!

**Comment by tin-cat** [comment]
Hi! I'm sorry to say there is no official guide to use Emailqueue without Composer, but you should be able to do so as long as you include all the needed libraries you'll found on composer.json.

Another way to install Emailqueue in a shared hosting would be to first install it in your local computer, where you'll be able to execute `composer update`, and then upload the resulting folder to the shared hosting. I haven't tested this but I'm guessing it should work!

Cheers!
