### ISSUE TITLE
PHPMailler Set Options

### ISSUE THREAD

**Issue by luizclaudioleme** [tin-cat/emailqueue#35]
I don't know if it's a issue, but I had to add the lines attached to work on port 587 in CPANEL when 

define("SMTP_PORT", 587); // The port of the SMTP server
define("SMTP_IS_AUTHENTICATION", true); // True to use SMTP server Authentication

$mail->SMTPOptions = array(
				'ssl' => array(
					'verify_peer' => false,
					'verify_peer_name' => false,
					'allow_self_signed' => true
				)
			);

I attach the example
![smtpoption](https://user-images.githubusercontent.com/53231869/146820545-4066d3ca-fedc-4694-a4ae-dc89adc3da5e.png)

**Comment by tin-cat** [comment]
Hi! Sorry for the late answer. It looks like your SMTP was using a self-signed SSL certificate, this is why you had to set those special settings for PHPMailer.
