### ISSUE TITLE
allow + in email address

### ISSUE THREAD

**Issue by Aaron-Ritter** [tin-cat/emailqueue#41]
The email standard allows for + in the email address to give the options to tag but still go to the same email account https://en.wikipedia.org/wiki/Email_address

https://github.com/tin-cat/emailqueue/blob/eae3d40c0fb4ec612d93872c45ef8d1924a52dd0/common.inc.php#L54

Would you be ok to add that to the regex?

**Comment by tin-cat** [comment]
Absolutely, please go ahead! Thank you for contributing! :D
